<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="AllanStevens.InfrastructureManagement._Default" %>

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Infrastructure Management</title>
    <%--<link href="style/style1.css" rel="stylesheet" type="text/css" />--%>
</head>
<body>    
    <form id="form1" runat="server" class="wrapper">
    
    <div id="header"><h1>Infrastructure Management</h1></div>
        
    <asp:XmlDataSource ID="XmlDataSourceNavigation" runat="server" 
        DataFile="~/data/navigation.xml"></asp:XmlDataSource>
    <asp:XmlDataSource 
         ID="XmlDataSourceServerLists" 
         runat="server" 
         DataFile="~/data/servers.xml" EnableCaching="False" >
    </asp:XmlDataSource>
    
    <!--TransformFile="~/data/servers_sort.xsl" -->
         
    <div id="sidemenu">
        
        <div id="menu">
        
        <div class="box_tl"></div>
        <div class="box_tr"></div>        
        <div class="box_content">
        <asp:TreeView ID="TreeView1" runat="server"
        DataSourceID="XmlDataSourceNavigation" ImageSet="Simple" 
        NodeIndent="10" AutoGenerateDataBindings="False" 
                onselectednodechanged="TreeView1_SelectedNodeChanged" >
            <ParentNodeStyle Font-Bold="False" />
            <HoverNodeStyle Font-Underline="True" ForeColor="#000000" Font-Bold="False" />
            <SelectedNodeStyle Font-Underline="True" 
                HorizontalPadding="0px" VerticalPadding="0px" ForeColor="#000000" />
            <DataBindings>
                <asp:TreeNodeBinding DataMember="menu" TextField="name" ValueField="xpath" />
                <asp:TreeNodeBinding DataMember="section" TextField="name" ValueField="xpath" />
                <asp:TreeNodeBinding DataMember="item" TextField="name" ValueField="xpath" />
            </DataBindings>
            <RootNodeStyle Font-Bold="False" />
            <NodeStyle Font-Names="Verdana" Font-Size="10pt" ForeColor="#000000" 
                HorizontalPadding="0px" NodeSpacing="0px" VerticalPadding="0px" 
                Font-Bold="False" />
            <LeafNodeStyle Font-Bold="False" />
        </asp:TreeView>
        </div>
        <div class="box_bl"></div>
        <div class="box_br"></div>        
       </div>
              
       <br />
       
       <asp:Literal runat="server" id="litQuickLinks"></asp:Literal>
       
       <!--Search-->
       
       <br />
       
       <div id="menu">
       <div class="box_tl"></div>
        <div class="box_tr"></div>        
        <div class="box_content" style="padding-left:15px;">
          
            <asp:TextBox ID="txtSearch" runat="server" Width="125px"></asp:TextBox>
            <asp:DropDownList ID="ddlSearch" runat="server" Width="125px" style="margin-top:5px;">
                <asp:ListItem Value=" ">All Locations</asp:ListItem>
                <asp:ListItem Value="[@location='Location 1']">Location 1</asp:ListItem>
                <asp:ListItem Value="[@location='Location 2']">Location 2</asp:ListItem>
                <asp:ListItem Value="[@location='Location 3']">Location 3</asp:ListItem>
                <asp:ListItem Value="[@location='Other']">Other</asp:ListItem>
            </asp:DropDownList><!-- todo - pull this infomration from data\xml-->
            <br />
            <asp:LinkButton ID="lnkSearch" runat="server" Width="125px" style="margin-top:5px;margin-left:85px;" 
                onclick="lnkSearch_Click">Search</asp:LinkButton>
        
        
        </div>
        <div class="box_bl"></div>
        <div class="box_br"></div>  
        </div> 
        </div>  
    </div>
    
    <div id="mainbody"> 
    
    <asp:GridView ID="GridView1" runat="server" 
        DataSourceID="XmlDataSourceServerLists" AutoGenerateColumns="False" 
        CellPadding="4" 
            onrowdeleting="GridView1_RowDeleting" onrowdeleted="GridView1_RowDeleted" 
            onselectedindexchanged="GridView1_SelectedIndexChanged" Width="100%" 
            AllowSorting="True" onsorting="GridView1_Sorting" 
            onprerender="GridView1_PreRender" onrowdatabound="GridView1_RowDataBound"             
            CssClass="gridrow">
                <columns>
                    <asp:BoundField DataField="catergory" HeaderText="catergory" 
                        SortExpression="catergory" Visible="False"></asp:BoundField>
                    <asp:BoundField DataField="location" HeaderText="location" 
                        SortExpression="location" Visible="False"></asp:BoundField>
                        
                    <asp:TemplateField HeaderText="" ItemStyle-Width="20px">
                        <ItemTemplate>
                            <img alt="" src="image/icons/<%# Eval("catergory").ToString() %>.gif"/>
                        </ItemTemplate>
                    </asp:TemplateField>
                        
                    <asp:BoundField DataField="name" HeaderText="Name" SortExpression="name" ItemStyle-Font-Bold="true">
                    </asp:BoundField>
                    <asp:BoundField DataField="ip" HeaderText="IP Address" SortExpression="ip" 
                        Visible="False">
                    </asp:BoundField>
                                        
                    <asp:BoundField DataField="iloip" HeaderText="ILO IP" SortExpression="iloip" 
                        Visible="False">
                    </asp:BoundField>
                    <asp:BoundField DataField="description" HeaderText="Description" 
                        SortExpression="description" Visible="True"></asp:BoundField>
                   <asp:TemplateField HeaderText="" Visible="false">
                        <ItemTemplate>                        
                        </ItemTemplate>
                    <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" Width="80px" />
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="" >
                        <ItemTemplate>                        
                        <%# Infrastructure_Management.Common.BuildLink(Eval("ip").ToString(), Infrastructure_Management.BuildLinkTypes.RDP) %>
                        <%# Infrastructure_Management.Common.BuildLink(Eval("iloip").ToString(), Infrastructure_Management.BuildLinkTypes.ILO) %>
                        <%# Infrastructure_Management.Common.BuildLink(Eval("url").ToString(), Infrastructure_Management.BuildLinkTypes.URL) %>
                         </ItemTemplate>
                        <ItemStyle Width="0px" Wrap="false" />
                    </asp:TemplateField>
                    <asp:TemplateField ShowHeader="False">
                        <ItemTemplate>
                            <asp:LinkButton ID="LinkButton1" runat="server" CausesValidation="False" 
                                CommandName="Delete" Text="Delete" OnClientClick="javascript:return confirm('Do you really want to delete the item?');" />
                        </ItemTemplate>
                        <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                    </asp:TemplateField>
                    <asp:TemplateField ShowHeader="False">
                        <ItemTemplate>
                            <asp:LinkButton ID="LinkButton2" runat="server" CausesValidation="False" 
                                CommandName="Select" Text="Edit"></asp:LinkButton>
                        </ItemTemplate>
                        <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                    </asp:TemplateField>
                    <asp:BoundField DataField="guid" HeaderText="" 
                        SortExpression="guid" Visible="True"></asp:BoundField>
                </columns>
                <FooterStyle Font-Bold="True" ForeColor="White" />
                <SelectedRowStyle Font-Bold="True" />                
                <AlternatingRowStyle BackColor="#FFE5E6" />
                <HeaderStyle ForeColor="White" />
            </asp:GridView>
            
            <asp:Literal runat="server" id="litNoResults">No items<br /><br /></asp:Literal>
            
            <asp:Panel ID="pnlAdd" runat="server" Visible="False">
                <table>
                    <tr>
                        <td>
                            Location</td>
                        <td>
                            <asp:DropDownList ID="ddlLocation" runat="server" AutoPostBack="True" 
                                onselectedindexchanged="ddlLocation_SelectedIndexChanged">
                                <asp:ListItem>Location 1</asp:ListItem>
                                <asp:ListItem>Location 2</asp:ListItem>
                                <asp:ListItem>Location 3</asp:ListItem>
                                <asp:ListItem>Other</asp:ListItem>
                            </asp:DropDownList><!-- todo - pull this infomration from data\xml-->
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Catergory</td>
                        <td>
                            <asp:DropDownList ID="ddlCatergory" runat="server"></asp:DropDownList>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Name</td>
                        <td>
                            <asp:TextBox ID="txtName" runat="server" Width="268px"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" 
                                ControlToValidate="txtName" ErrorMessage="Name missing" ValidationGroup="Add"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            IP Address</td>
                        <td>
                            <asp:TextBox ID="txtIP" runat="server" Width="268px"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            ILO IP Address</td>
                        <td>
                            https://
                            <asp:TextBox ID="txtILOIP" runat="server" Width="268px"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Application Url</td>
                        <td>
                            <asp:TextBox ID="txtURL" runat="server" Width="268px"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top">
                            Description</td>
                        <td>
                            <asp:TextBox ID="txtDescription" runat="server" Height="72px" Width="381px"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td valign="top">
                            Unique Identifier </td>
                        <td>
                            <asp:TextBox ID="txtGUID" runat="server" Width="268px" BorderStyle="None" 
                                Enabled="False" ReadOnly="True" BorderColor="White" BorderWidth="1px"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            &nbsp;</td>
                        <td>
                            &nbsp;</td>
                    </tr>
                </table>
             
             <asp:LinkButton ID="lnkCancel" runat="server" CausesValidation="False" 
                    onclick="lnkCancel_Click" BorderColor="White" BorderStyle="Solid" 
                    BorderWidth="4px">Cancel</asp:LinkButton>
                            <asp:LinkButton ID="lnkSave" runat="server" onclick="lnkSave_Click" 
                                ValidationGroup="Add" BorderColor="White" BorderStyle="Solid" 
                    BorderWidth="4px">Save</asp:LinkButton>
                                      
            </asp:Panel>
            
             <br />
                <asp:LinkButton ID="lnkAddItem" runat="server" BorderColor="White" 
                    BorderWidth="4px" CausesValidation="False" onclick="lnkAddItem_Click">Add 
                new item</asp:LinkButton>
                <asp:LinkButton ID="lnkShowAll" runat="server" BorderColor="White" 
                    BorderWidth="4px" CausesValidation="False" onclick="lnkShowAll_Click">Show 
                All Fields</asp:LinkButton>
                <asp:label ID="lblCount" runat="server"></asp:label>
    </div>
    
    </form>
</body>
</html>
